# Generated by Django 3.1.7 on 2021-03-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20210308_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPriceView',
            fields=[
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rowid', models.BigIntegerField(blank=True, null=True)),
                ('cmc_rank', models.BigIntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('volume_24h', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=50, null=True)),
                ('load_date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_price_view',
                'ordering': ['cmc_rank'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LatestPriceView',
            fields=[
                ('rowid', models.BigIntegerField(blank=True, null=True)),
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('num_market_pairs', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.CharField(blank=True, max_length=100, null=True)),
                ('max_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('circulating_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('total_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=200, null=True)),
                ('cmc_rank', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('volume_24h', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_change_1h', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_change_24h', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_change_7d', models.CharField(blank=True, max_length=50, null=True)),
                ('percent_change_30d', models.CharField(blank=True, max_length=50, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=50, null=True)),
                ('price_last_updated', models.CharField(blank=True, max_length=50, null=True)),
                ('load_date', models.DateField(blank=True, null=True)),
                ('load_date_time', models.DateTimeField(blank=True, null=True)),
                ('latest_load_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'latest_price_view',
                'ordering': ['cmc_rank'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
