# Generated by Django 3.1.7 on 2021-03-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('dept', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
                ('create_ts', models.DateTimeField(auto_now_add=True)),
                ('modified_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
